//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon_phieuthue
    {
        public long MaHoaDon { get; set; }
        public int MaPhieuThue { get; set; }
        public string GhiChu { get; set; }
    
        public virtual hoadon hoadon { get; set; }
        public virtual phieuthue phieuthue { get; set; }
    }
}
