//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoadon()
        {
            this.hoadon_phieuthue = new HashSet<hoadon_phieuthue>();
        }
    
        public long MaHoaDon { get; set; }
        public Nullable<int> SoNgayThue { get; set; }
        public Nullable<float> TongTien { get; set; }
        public Nullable<int> PhuThu { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public int MaKH { get; set; }
        public int MaPhong { get; set; }
        public int MaNV { get; set; }
    
        public virtual khachhang khachhang { get; set; }
        public virtual nguoidung nguoidung { get; set; }
        public virtual phong phong { get; set; }
        public virtual phuthu phuthu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadon_phieuthue> hoadon_phieuthue { get; set; }
    }
}
